default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USER", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: github_workflow_playground_development

test:
  <<: *default
  database: github_workflow_playground_test

production:
  <<: *default
  database: github_workflow_playground_production
